-- ============================================================================
-- Real seed: FC Barcelona històric (multi-temporada).
-- Auto-generated by scripts/build-historic-seeds.mjs from
-- scripts/historic-squads-raw.json (sourced from Wikipedia).
-- Generated: 2026-05-12T22:54:09.543Z
--
-- Each season is a separate tag. The composite "barca-historic"
-- theme (in 10_historic_themes.sql) aggregates them so a single room
-- can draw from any of these eras at once.
-- ============================================================================

insert into public.tags (slug, display_name, category)
values ('barca-2010-11', 'FC Barcelona 2010-11', 'club_season')
on conflict (slug) do nothing;

insert into public.tags (slug, display_name, category)
values ('barca-2014-15', 'FC Barcelona 2014-15', 'club_season')
on conflict (slug) do nothing;

-- FC Barcelona 2010-11 (20 jugadors)
insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('bar1011-valdes', 'Víctor Valdés', 'GK', 'FC Barcelona 2010-11', 18),
	('bar1011-alves', 'Dani Alves', 'RB', 'FC Barcelona 2010-11', 30),
	('bar1011-pique', 'Gerard Piqué', 'CB', 'FC Barcelona 2010-11', 35),
	('bar1011-puyol', 'Carles Puyol', 'CB', 'FC Barcelona 2010-11', 20),
	('bar1011-xavi', 'Xavi', 'CM', 'FC Barcelona 2010-11', 35),
	('bar1011-villa', 'David Villa', 'LW', 'FC Barcelona 2010-11', 30),
	('bar1011-iniesta', 'Andrés Iniesta', 'CM', 'FC Barcelona 2010-11', 50),
	('bar1011-bojan', 'Bojan', 'ST', 'FC Barcelona 2010-11', 12),
	('bar1011-messi', 'Lionel Messi', 'RW', 'FC Barcelona 2010-11', 80),
	('bar1011-jeffren', 'Jeffrén', 'RW', 'FC Barcelona 2010-11', 15),
	('bar1011-pinto', 'José Manuel Pinto', 'GK', 'FC Barcelona 2010-11', 5),
	('bar1011-mascherano', 'Javier Mascherano', 'CM', 'FC Barcelona 2010-11', 25),
	('bar1011-keita', 'Seydou Keita', 'CM', 'FC Barcelona 2010-11', 12),
	('bar1011-busquets', 'Sergio Busquets', 'CM', 'FC Barcelona 2010-11', 20),
	('bar1011-pedro', 'Pedro', 'RW', 'FC Barcelona 2010-11', 25),
	('bar1011-milito', 'Gabriel Milito', 'CB', 'FC Barcelona 2010-11', 10),
	('bar1011-maxwell', 'Maxwell', 'LB', 'FC Barcelona 2010-11', 8),
	('bar1011-afellay', 'Ibrahim Afellay', 'CM', 'FC Barcelona 2010-11', 10),
	('bar1011-adriano', 'Adriano', 'LB', 'FC Barcelona 2010-11', 8),
	('bar1011-abidal', 'Eric Abidal', 'LB', 'FC Barcelona 2010-11', 15)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'barca-2010-11'
	and p.metadata ->> 'dev_seed_id' like 'bar1011-%'
on conflict do nothing;

-- FC Barcelona 2014-15 (33 jugadors)
insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('bar1415-samper', 'Sergi Samper', 'CM', 'FC Barcelona 2014-15', 12),
	('bar1415-traore', 'Adama Traoré', 'RW', 'FC Barcelona 2014-15', 15),
	('bar1415-grimaldo', 'Álex Grimaldo', 'LW', 'FC Barcelona 2014-15', 15),
	('bar1415-sandro', 'Sandro', 'ST', 'FC Barcelona 2014-15', 15),
	('bar1415-halilovic', 'Alen Halilović', 'CM', 'FC Barcelona 2014-15', 12),
	('bar1415-munir', 'Munir', 'RW', 'FC Barcelona 2014-15', 15),
	('bar1415-ie', 'Edgar Ié', 'CB', 'FC Barcelona 2014-15', 10),
	('bar1415-diagne', 'Diawandou Diagne', 'CB', 'FC Barcelona 2014-15', 10),
	('bar1415-ondoa', 'Fabrice Ondoa', 'GK', 'FC Barcelona 2014-15', 5),
	('bar1415-gumbau', 'Gerard Gumbau', 'CM', 'FC Barcelona 2014-15', 12),
	('bar1415-stegen', 'Marc-André ter Stegen', 'GK', 'FC Barcelona 2014-15', 18),
	('bar1415-bravo', 'Claudio Bravo', 'GK', 'FC Barcelona 2014-15', 12),
	('bar1415-masip', 'Jordi Masip', 'GK', 'FC Barcelona 2014-15', 5),
	('bar1415-montoya', 'Martín Montoya', 'RB', 'FC Barcelona 2014-15', 8),
	('bar1415-pique', 'Gerard Piqué', 'CB', 'FC Barcelona 2014-15', 30),
	('bar1415-mascherano', 'Javier Mascherano', 'CB', 'FC Barcelona 2014-15', 25),
	('bar1415-bartra', 'Marc Bartra', 'CB', 'FC Barcelona 2014-15', 10),
	('bar1415-douglas', 'Douglas', 'CB', 'FC Barcelona 2014-15', 10),
	('bar1415-alba', 'Jordi Alba', 'CB', 'FC Barcelona 2014-15', 30),
	('bar1415-roberto', 'Sergi Roberto', 'CB', 'FC Barcelona 2014-15', 10),
	('bar1415-adriano', 'Adriano', 'CB', 'FC Barcelona 2014-15', 10),
	('bar1415-alves', 'Dani Alves', 'CB', 'FC Barcelona 2014-15', 22),
	('bar1415-vermaelen', 'Thomas Vermaelen', 'CB', 'FC Barcelona 2014-15', 10),
	('bar1415-mathieu', 'Jérémy Mathieu', 'CB', 'FC Barcelona 2014-15', 10),
	('bar1415-rakitic', 'Ivan Rakitić', 'CM', 'FC Barcelona 2014-15', 25),
	('bar1415-busquets', 'Sergio Busquets', 'CM', 'FC Barcelona 2014-15', 25),
	('bar1415-xavi', 'Xavi', 'CM', 'FC Barcelona 2014-15', 18),
	('bar1415-iniesta', 'Andrés Iniesta', 'CM', 'FC Barcelona 2014-15', 35),
	('bar1415-rafinha', 'Rafinha', 'CM', 'FC Barcelona 2014-15', 8),
	('bar1415-pedro', 'Pedro', 'RW', 'FC Barcelona 2014-15', 25),
	('bar1415-suarez', 'Luis Suárez', 'ST', 'FC Barcelona 2014-15', 60),
	('bar1415-messi', 'Lionel Messi', 'RW', 'FC Barcelona 2014-15', 120),
	('bar1415-neymar', 'Neymar', 'ST', 'FC Barcelona 2014-15', 70)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'barca-2014-15'
	and p.metadata ->> 'dev_seed_id' like 'bar1415-%'
on conflict do nothing;

