-- ============================================================================
-- Real seed: Real Madrid històric (multi-temporada).
-- Auto-generated by scripts/build-historic-seeds.mjs from
-- scripts/historic-squads-raw.json (sourced from Wikipedia).
-- Generated: 2026-05-12T22:54:09.565Z
--
-- Each season is a separate tag. The composite "madrid-historic"
-- theme (in 10_historic_themes.sql) aggregates them so a single room
-- can draw from any of these eras at once.
-- ============================================================================

insert into public.tags (slug, display_name, category)
values ('madrid-2013-14', 'Real Madrid 2013-14', 'club_season')
on conflict (slug) do nothing;

insert into public.tags (slug, display_name, category)
values ('madrid-2016-17', 'Real Madrid 2016-17', 'club_season')
on conflict (slug) do nothing;

-- Real Madrid 2013-14 (23 jugadors)
insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('rm1314-casillas', 'Iker Casillas', 'GK', 'Real Madrid 2013-14', 20),
	('rm1314-varane', 'Raphaël Varane', 'CB', 'Real Madrid 2013-14', 25),
	('rm1314-pepe', 'Pepe', 'CB', 'Real Madrid 2013-14', 18),
	('rm1314-ramos', 'Sergio Ramos', 'CB', 'Real Madrid 2013-14', 35),
	('rm1314-coentrao', 'Fábio Coentrão', 'LB', 'Real Madrid 2013-14', 18),
	('rm1314-khedira', 'Sami Khedira', 'CM', 'Real Madrid 2013-14', 18),
	('rm1314-ronaldo', 'Cristiano Ronaldo', 'LW', 'Real Madrid 2013-14', 100),
	('rm1314-benzema', 'Karim Benzema', 'ST', 'Real Madrid 2013-14', 35),
	('rm1314-bale', 'Gareth Bale', 'RW', 'Real Madrid 2013-14', 90),
	('rm1314-marcelo', 'Marcelo', 'LB', 'Real Madrid 2013-14', 20),
	('rm1314-jesus', 'Jesús', 'GK', 'Real Madrid 2013-14', 5),
	('rm1314-alonso', 'Xabi Alonso', 'CM', 'Real Madrid 2013-14', 25),
	('rm1314-carvajal', 'Dani Carvajal', 'RB', 'Real Madrid 2013-14', 15),
	('rm1314-casemiro', 'Casemiro', 'CM', 'Real Madrid 2013-14', 8),
	('rm1314-arbeloa', 'Álvaro Arbeloa', 'RB', 'Real Madrid 2013-14', 8),
	('rm1314-fernandez', 'Nacho Fernandez', 'CB', 'Real Madrid 2013-14', 10),
	('rm1314-modric', 'Luka Modrić', 'CM', 'Real Madrid 2013-14', 35),
	('rm1314-jese', 'Jesé', 'LW', 'Real Madrid 2013-14', 15),
	('rm1314-morata', 'Álvaro Morata', 'ST', 'Real Madrid 2013-14', 15),
	('rm1314-maria', 'Ángel Di María', 'RW', 'Real Madrid 2013-14', 35),
	('rm1314-isco', 'Isco', 'LW', 'Real Madrid 2013-14', 30),
	('rm1314-illarramendi', 'Asier Illarramendi', 'CM', 'Real Madrid 2013-14', 18),
	('rm1314-lopez', 'Diego López', 'GK', 'Real Madrid 2013-14', 12)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'madrid-2013-14'
	and p.metadata ->> 'dev_seed_id' like 'rm1314-%'
on conflict do nothing;

-- Real Madrid 2016-17 (27 jugadors)
insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('rm1617-navas', 'Keylor Navas', 'GK', 'Real Madrid 2016-17', 20),
	('rm1617-carvajal', 'Dani Carvajal', 'RB', 'Real Madrid 2016-17', 25),
	('rm1617-ramos', 'Sergio Ramos', 'CB', 'Real Madrid 2016-17', 40),
	('rm1617-varane', 'Raphaël Varane', 'CB', 'Real Madrid 2016-17', 35),
	('rm1617-nacho', 'Nacho', 'CB', 'Real Madrid 2016-17', 18),
	('rm1617-marcelo', 'Marcelo', 'LB', 'Real Madrid 2016-17', 30),
	('rm1617-kroos', 'Toni Kroos', 'CM', 'Real Madrid 2016-17', 60),
	('rm1617-casemiro', 'Casemiro', 'CM', 'Real Madrid 2016-17', 30),
	('rm1617-modric', 'Luka Modrić', 'CM', 'Real Madrid 2016-17', 50),
	('rm1617-ronaldo', 'Cristiano Ronaldo', 'LW', 'Real Madrid 2016-17', 120),
	('rm1617-benzema', 'Karim Benzema', 'ST', 'Real Madrid 2016-17', 45),
	('rm1617-casilla', 'Kiko Casilla', 'GK', 'Real Madrid 2016-17', 5),
	('rm1617-kovacic', 'Mateo Kovačić', 'CM', 'Real Madrid 2016-17', 22),
	('rm1617-isco', 'Isco', 'LW', 'Real Madrid 2016-17', 40),
	('rm1617-bale', 'Gareth Bale', 'RW', 'Real Madrid 2016-17', 80),
	('rm1617-danilo', 'Danilo', 'RB', 'Real Madrid 2016-17', 8),
	('rm1617-morata', 'Álvaro Morata', 'ST', 'Real Madrid 2016-17', 35),
	('rm1617-pepe', 'Pepe', 'CB', 'Real Madrid 2016-17', 12),
	('rm1617-rodriguez', 'James Rodríguez', 'CM', 'Real Madrid 2016-17', 50),
	('rm1617-vazquez', 'Lucas Vázquez', 'RW', 'Real Madrid 2016-17', 14),
	('rm1617-asensio', 'Marco Asensio', 'RW', 'Real Madrid 2016-17', 30),
	('rm1617-coentrao', 'Fábio Coentrão', 'CB', 'Real Madrid 2016-17', 10),
	('rm1617-mariano', 'Mariano', 'ST', 'Real Madrid 2016-17', 15),
	('rm1617-tejero', 'Álvaro Tejero', 'CB', 'Real Madrid 2016-17', 10),
	('rm1617-yanez', 'Rubén Yáñez', 'GK', 'Real Madrid 2016-17', 5),
	('rm1617-degaard', 'Martin Ødegaard', 'CM', 'Real Madrid 2016-17', 12),
	('rm1617-fernandez', 'Enzo Fernández', 'CM', 'Real Madrid 2016-17', 12)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'madrid-2016-17'
	and p.metadata ->> 'dev_seed_id' like 'rm1617-%'
on conflict do nothing;

