-- ============================================================================
-- Real seed: Villarreal històric (multi-temporada).
-- Auto-generated by scripts/build-historic-seeds.mjs from
-- scripts/historic-squads-raw.json (sourced from Wikipedia).
-- Generated: 2026-05-12T22:54:09.570Z
--
-- Each season is a separate tag. The composite "villarreal-historic"
-- theme (in 10_historic_themes.sql) aggregates them so a single room
-- can draw from any of these eras at once.
-- ============================================================================

insert into public.tags (slug, display_name, category)
values ('villarreal-2005-06', 'Villarreal CF 2005-06', 'club_season')
on conflict (slug) do nothing;

insert into public.tags (slug, display_name, category)
values ('villarreal-2007-08', 'Villarreal CF 2007-08', 'club_season')
on conflict (slug) do nothing;

insert into public.tags (slug, display_name, category)
values ('villarreal-2010-11', 'Villarreal CF 2010-11', 'club_season')
on conflict (slug) do nothing;

-- Villarreal CF 2005-06 (35 jugadors)
insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('vil0506-vallejo', 'Javier López Vallejo', 'GK', 'Villarreal CF 2005-06', 5),
	('vil0506-rodriguez', 'Gonzalo Rodríguez', 'CB', 'Villarreal CF 2005-06', 8),
	('vil0506-arruabarrena', 'Rodolfo Arruabarrena', 'CB', 'Villarreal CF 2005-06', 10),
	('vil0506-amposta', 'César Arzo Amposta', 'CB', 'Villarreal CF 2005-06', 10),
	('vil0506-forlan', 'Diego Forlán', 'ST', 'Villarreal CF 2005-06', 25),
	('vil0506-josico', 'Josico', 'CM', 'Villarreal CF 2005-06', 12),
	('vil0506-guayre', 'Antonio Guayre', 'ST', 'Villarreal CF 2005-06', 15),
	('vil0506-riquelme', 'Juan Román Riquelme', 'CM', 'Villarreal CF 2005-06', 30),
	('vil0506-franco', 'Guillermo Franco', 'ST', 'Villarreal CF 2005-06', 10),
	('vil0506-roger', 'Roger', 'CM', 'Villarreal CF 2005-06', 12),
	('vil0506-calleja', 'Javier Calleja', 'RW', 'Villarreal CF 2005-06', 15),
	('vil0506-sorin', 'Juan Pablo Sorín', 'CB', 'Villarreal CF 2005-06', 8),
	('vil0506-viera', 'Sebastián Viera', 'GK', 'Villarreal CF 2005-06', 5),
	('vil0506-font', 'Héctor Font', 'CM', 'Villarreal CF 2005-06', 12),
	('vil0506-alvarez', 'Quique Álvarez', 'CB', 'Villarreal CF 2005-06', 10),
	('vil0506-venta', 'Javi Venta', 'CB', 'Villarreal CF 2005-06', 10),
	('vil0506-tacchinardi', 'Alessio Tacchinardi', 'CM', 'Villarreal CF 2005-06', 6),
	('vil0506-senna', 'Marcos Senna', 'CM', 'Villarreal CF 2005-06', 12),
	('vil0506-cazorla', 'Santi Cazorla', 'CM', 'Villarreal CF 2005-06', 6),
	('vil0506-pena', 'Juan Manuel Peña', 'CB', 'Villarreal CF 2005-06', 10),
	('vil0506-mari', 'José Mari', 'ST', 'Villarreal CF 2005-06', 15),
	('vil0506-josemi', 'Josemi', 'CB', 'Villarreal CF 2005-06', 10),
	('vil0506-barbosa', 'Mariano Barbosa', 'GK', 'Villarreal CF 2005-06', 5),
	('vil0506-nadal', 'Xisco Nadal', 'ST', 'Villarreal CF 2005-06', 15),
	('vil0506-jony', 'Jony', 'ST', 'Villarreal CF 2005-06', 15),
	('vil0506-alcantara', 'Carlos Alcántara', 'CB', 'Villarreal CF 2005-06', 10),
	('vil0506-carlos', 'Juan Carlos', 'GK', 'Villarreal CF 2005-06', 5),
	('vil0506-rubio', 'Javi Rubio', 'CM', 'Villarreal CF 2005-06', 12),
	('vil0506-nino', 'Nino', 'CB', 'Villarreal CF 2005-06', 10),
	('vil0506-lopez', 'Óscar López', 'ST', 'Villarreal CF 2005-06', 15),
	('vil0506-marquitos', 'Marquitos', 'CM', 'Villarreal CF 2005-06', 12),
	('vil0506-fuster', 'David Fuster', 'CM', 'Villarreal CF 2005-06', 12),
	('vil0506-figueroa', 'Luciano Figueroa', 'ST', 'Villarreal CF 2005-06', 15),
	('vil0506-kromkamp', 'Jan Kromkamp', 'CB', 'Villarreal CF 2005-06', 10),
	('vil0506-valencia', 'Luis Antonio Valencia', 'CM', 'Villarreal CF 2005-06', 12)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'villarreal-2005-06'
	and p.metadata ->> 'dev_seed_id' like 'vil0506-%'
on conflict do nothing;

-- Villarreal CF 2007-08 (32 jugadors)
insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('vil0708-viera', 'Sebastián Viera', 'GK', 'Villarreal CF 2007-08', 5),
	('vil0708-rodriguez', 'Gonzalo Rodríguez', 'CB', 'Villarreal CF 2007-08', 10),
	('vil0708-josemi', 'Josemi', 'CB', 'Villarreal CF 2007-08', 10),
	('vil0708-godin', 'Diego Godín', 'CB', 'Villarreal CF 2007-08', 12),
	('vil0708-capdevila', 'Joan Capdevila', 'LB', 'Villarreal CF 2007-08', 12),
	('vil0708-josico', 'Josico', 'CM', 'Villarreal CF 2007-08', 12),
	('vil0708-pires', 'Robert Pires', 'LW', 'Villarreal CF 2007-08', 8),
	('vil0708-cazorla', 'Santi Cazorla', 'CM', 'Villarreal CF 2007-08', 20),
	('vil0708-franco', 'Guillermo Franco', 'ST', 'Villarreal CF 2007-08', 15),
	('vil0708-cani', 'Cani', 'CM', 'Villarreal CF 2007-08', 12),
	('vil0708-tomasson', 'Jon Dahl Tomasson', 'ST', 'Villarreal CF 2007-08', 6),
	('vil0708-cygan', 'Pascal Cygan', 'LB', 'Villarreal CF 2007-08', 8),
	('vil0708-lopez', 'Diego López', 'GK', 'Villarreal CF 2007-08', 5),
	('vil0708-fernandez', 'Matías Fernández', 'CM', 'Villarreal CF 2007-08', 12),
	('vil0708-kahveci', 'Nihat Kahveci', 'ST', 'Villarreal CF 2007-08', 14),
	('vil0708-venta', 'Javi Venta', 'CB', 'Villarreal CF 2007-08', 10),
	('vil0708-angel', 'Ángel', 'CM', 'Villarreal CF 2007-08', 12),
	('vil0708-senna', 'Marcos Senna', 'CM', 'Villarreal CF 2007-08', 15),
	('vil0708-fuentes', 'Fabricio Fuentes', 'CB', 'Villarreal CF 2007-08', 10),
	('vil0708-bruno', 'Bruno', 'CM', 'Villarreal CF 2007-08', 12),
	('vil0708-rossi', 'Giuseppe Rossi', 'ST', 'Villarreal CF 2007-08', 12),
	('vil0708-eguren', 'Sebastián Eguren', 'CM', 'Villarreal CF 2007-08', 12),
	('vil0708-carlos', 'Juan Carlos', 'GK', 'Villarreal CF 2007-08', 5),
	('vil0708-bella', 'Alberto de la Bella', 'CB', 'Villarreal CF 2007-08', 10),
	('vil0708-kiko', 'Kiko', 'CB', 'Villarreal CF 2007-08', 10),
	('vil0708-rocha', 'Rocha', 'CB', 'Villarreal CF 2007-08', 10),
	('vil0708-condesso', 'Feliciano Condesso', 'CM', 'Villarreal CF 2007-08', 12),
	('vil0708-ruben', 'Rubén', 'ST', 'Villarreal CF 2007-08', 15),
	('vil0708-riquelme', 'Juan Román Riquelme', 'CM', 'Villarreal CF 2007-08', 18),
	('vil0708-mari', 'José Mari', 'ST', 'Villarreal CF 2007-08', 15),
	('vil0708-mavuba', 'Rio Mavuba', 'CM', 'Villarreal CF 2007-08', 12),
	('vil0708-nadal', 'Xisco Nadal', 'ST', 'Villarreal CF 2007-08', 15)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'villarreal-2007-08'
	and p.metadata ->> 'dev_seed_id' like 'vil0708-%'
on conflict do nothing;

-- Villarreal CF 2010-11 (28 jugadors)
insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('vil1011-oliva', 'Xavi Oliva', 'GK', 'Villarreal CF 2010-11', 5),
	('vil1011-rodriguez', 'Gonzalo Rodríguez', 'CB', 'Villarreal CF 2010-11', 10),
	('vil1011-oriol', 'Joan Oriol', 'CB', 'Villarreal CF 2010-11', 10),
	('vil1011-musacchio', 'Mateo Musacchio', 'CB', 'Villarreal CF 2010-11', 10),
	('vil1011-marchena', 'Carlos Marchena', 'CB', 'Villarreal CF 2010-11', 8),
	('vil1011-lopez', 'Ángel López', 'CB', 'Villarreal CF 2010-11', 10),
	('vil1011-nilmar', 'Nilmar', 'ST', 'Villarreal CF 2010-11', 18),
	('vil1011-cazorla', 'Santi Cazorla', 'CM', 'Villarreal CF 2010-11', 22),
	('vil1011-ruben', 'Marco Ruben', 'ST', 'Villarreal CF 2010-11', 10),
	('vil1011-cani', 'Cani', 'CM', 'Villarreal CF 2010-11', 8),
	('vil1011-capdevila', 'Joan Capdevila', 'LB', 'Villarreal CF 2010-11', 8),
	('vil1011-lopez2', 'Diego López', 'GK', 'Villarreal CF 2010-11', 8),
	('vil1011-catala', 'José Catalá', 'CB', 'Villarreal CF 2010-11', 10),
	('vil1011-matilla', 'Javier Matilla', 'CM', 'Villarreal CF 2010-11', 12),
	('vil1011-senna', 'Marcos Senna', 'CM', 'Villarreal CF 2010-11', 8),
	('vil1011-valero', 'Borja Valero', 'CM', 'Villarreal CF 2010-11', 12),
	('vil1011-soriano', 'Bruno Soriano', 'CM', 'Villarreal CF 2010-11', 8),
	('vil1011-rossi', 'Giuseppe Rossi', 'ST', 'Villarreal CF 2010-11', 25),
	('vil1011-cicinho', 'Cicinho', 'CB', 'Villarreal CF 2010-11', 10),
	('vil1011-carlos', 'Juan Carlos', 'GK', 'Villarreal CF 2010-11', 5),
	('vil1011-kiko', 'Kiko', 'CB', 'Villarreal CF 2010-11', 10),
	('vil1011-gaspar', 'Mario Gaspar', 'RB', 'Villarreal CF 2010-11', 8),
	('vil1011-gullon', 'Marcos Gullón', 'CM', 'Villarreal CF 2010-11', 12),
	('vil1011-marino', 'Diego Mariño', 'GK', 'Villarreal CF 2010-11', 5),
	('vil1011-falque', 'Iago Falqué', 'ST', 'Villarreal CF 2010-11', 15),
	('vil1011-nielsen', 'Nicki Bille Nielsen', 'ST', 'Villarreal CF 2010-11', 15),
	('vil1011-mubarak', 'Wakaso Mubarak', 'CM', 'Villarreal CF 2010-11', 12),
	('vil1011-marquez', 'Cristóbal Márquez', 'CM', 'Villarreal CF 2010-11', 12)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'villarreal-2010-11'
	and p.metadata ->> 'dev_seed_id' like 'vil1011-%'
on conflict do nothing;

