-- ============================================================================
-- Real seed: UCL 2025-26 favorites — 7 top European clubs.
-- Auto-generated by scripts/build-ucl-seeds.mjs from
-- scripts/ucl-squads-raw.json (sourced from Wikipedia).
-- Generated: 2026-05-13T09:13:20.084Z
-- ============================================================================

-- Manchester City 2025-26 (43 jugadors)
insert into public.tags (slug, display_name, category)
values ('mancity-25-26', 'Manchester City 2025-26', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('mancity2526-trafford', 'James Trafford', 'GK', 'Manchester City 2025-26', 18),
	('mancity2526-dias', 'Rúben Dias', 'CB', 'Manchester City 2025-26', 70),
	('mancity2526-reijnders', 'Tijjani Reijnders', 'CM', 'Manchester City 2025-26', 65),
	('mancity2526-stones', 'John Stones', 'CB', 'Manchester City 2025-26', 40),
	('mancity2526-ake', 'Nathan Aké', 'LB', 'Manchester City 2025-26', 30),
	('mancity2526-marmoush', 'Omar Marmoush', 'ST', 'Manchester City 2025-26', 45),
	('mancity2526-kovacic', 'Mateo Kovačić', 'CM', 'Manchester City 2025-26', 30),
	('mancity2526-haaland', 'Erling Haaland', 'ST', 'Manchester City 2025-26', 180),
	('mancity2526-cherki', 'Rayan Cherki', 'CM', 'Manchester City 2025-26', 50),
	('mancity2526-doku', 'Jérémy Doku', 'CM', 'Manchester City 2025-26', 45),
	('mancity2526-bettinelli', 'Marcus Bettinelli', 'GK', 'Manchester City 2025-26', 15),
	('mancity2526-gonzalez', 'Nico González', 'CM', 'Manchester City 2025-26', 30),
	('mancity2526-guehi', 'Marc Guéhi', 'CB', 'Manchester City 2025-26', 40),
	('mancity2526-rodri', 'Rodri', 'CM', 'Manchester City 2025-26', 100),
	('mancity2526-silva', 'Bernardo Silva', 'CM', 'Manchester City 2025-26', 70),
	('mancity2526-aitnouri', 'Rayan Aït-Nouri', 'LW', 'Manchester City 2025-26', 35),
	('mancity2526-gvardiol', 'Joško Gvardiol', 'LB', 'Manchester City 2025-26', 70),
	('mancity2526-donnarumma', 'Gianluigi Donnarumma', 'GK', 'Manchester City 2025-26', 35),
	('mancity2526-savinho', 'Savinho', 'CM', 'Manchester City 2025-26', 35),
	('mancity2526-nunes', 'Matheus Nunes', 'CM', 'Manchester City 2025-26', 25),
	('mancity2526-oreilly', 'Nico O''Reilly', 'CM', 'Manchester City 2025-26', 30),
	('mancity2526-nypan', 'Sverre Nypan', 'CM', 'Manchester City 2025-26', 30),
	('mancity2526-semenyo', 'Antoine Semenyo', 'CM', 'Manchester City 2025-26', 40),
	('mancity2526-khusanov', 'Abdukodir Khusanov', 'RB', 'Manchester City 2025-26', 20),
	('mancity2526-foden', 'Phil Foden', 'CM', 'Manchester City 2025-26', 110),
	('mancity2526-lewis', 'Rico Lewis', 'CB', 'Manchester City 2025-26', 25),
	('mancity2526-mcaidoo', 'Ryan McAidoo', 'RW', 'Manchester City 2025-26', 40),
	('mancity2526-gray', 'Charlie Gray', 'CM', 'Manchester City 2025-26', 30),
	('mancity2526-braithwaite', 'Kaden Braithwaite', 'CB', 'Manchester City 2025-26', 25),
	('mancity2526-alleyne', 'Max Alleyne', 'CB', 'Manchester City 2025-26', 25),
	('mancity2526-mbete', 'Luke Mbete', 'LB', 'Manchester City 2025-26', 20),
	('mancity2526-brits', 'Spike Brits', 'GK', 'Manchester City 2025-26', 15),
	('mancity2526-reis', 'Vitor Reis', 'CB', 'Manchester City 2025-26', 25),
	('mancity2526-echeverri', 'Claudio Echeverri', 'CM', 'Manchester City 2025-26', 30),
	('mancity2526-phillips', 'Kalvin Phillips', 'CM', 'Manchester City 2025-26', 30),
	('mancity2526-simpsonpusey', 'Jahmai Simpson-Pusey', 'CB', 'Manchester City 2025-26', 25),
	('mancity2526-kabore', 'Issa Kaboré', 'RW', 'Manchester City 2025-26', 40),
	('mancity2526-mfuni', 'Stephen Mfuni', 'LB', 'Manchester City 2025-26', 20),
	('mancity2526-burns', 'Finley Burns', 'CB', 'Manchester City 2025-26', 25),
	('mancity2526-wilsonesbran', 'Josh Wilson-Esbrand', 'LB', 'Manchester City 2025-26', 20),
	('mancity2526-akanji', 'Manuel Akanji', 'CB', 'Manchester City 2025-26', 30),
	('mancity2526-bah', 'Juma Bah', 'CB', 'Manchester City 2025-26', 25),
	('mancity2526-grealish', 'Jack Grealish', 'LW', 'Manchester City 2025-26', 40)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'mancity-25-26'
	and p.metadata ->> 'dev_seed_id' like 'mancity2526-%'
on conflict do nothing;

-- Arsenal 2025-26 (38 jugadors)
insert into public.tags (slug, display_name, category)
values ('arsenal-25-26', 'Arsenal 2025-26', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('arsenal2526-raya', 'David Raya', 'GK', 'Arsenal 2025-26', 30),
	('arsenal2526-saliba', 'William Saliba', 'CB', 'Arsenal 2025-26', 80),
	('arsenal2526-mosquera', 'Cristhian Mosquera', 'CB', 'Arsenal 2025-26', 25),
	('arsenal2526-white', 'Ben White', 'CB', 'Arsenal 2025-26', 45),
	('arsenal2526-hincapie', 'Piero Hincapié', 'LB', 'Arsenal 2025-26', 30),
	('arsenal2526-magalhaes', 'Gabriel Magalhães', 'CB', 'Arsenal 2025-26', 65),
	('arsenal2526-saka', 'Bukayo Saka', 'RW', 'Arsenal 2025-26', 110),
	('arsenal2526-degaard', 'Martin Ødegaard', 'CM', 'Arsenal 2025-26', 90),
	('arsenal2526-jesus', 'Gabriel Jesus', 'ST', 'Arsenal 2025-26', 35),
	('arsenal2526-eze', 'Eberechi Eze', 'CM', 'Arsenal 2025-26', 60),
	('arsenal2526-martinelli', 'Gabriel Martinelli', 'LW', 'Arsenal 2025-26', 55),
	('arsenal2526-timber', 'Jurriën Timber', 'CB', 'Arsenal 2025-26', 40),
	('arsenal2526-arrizabalaga', 'Kepa Arrizabalaga', 'GK', 'Arsenal 2025-26', 15),
	('arsenal2526-gyokeres', 'Viktor Gyökeres', 'ST', 'Arsenal 2025-26', 70),
	('arsenal2526-nrgaard', 'Christian Nørgaard', 'CM', 'Arsenal 2025-26', 30),
	('arsenal2526-trossard', 'Leandro Trossard', 'LW', 'Arsenal 2025-26', 25),
	('arsenal2526-madueke', 'Noni Madueke', 'RW', 'Arsenal 2025-26', 35),
	('arsenal2526-merino', 'Mikel Merino', 'CM', 'Arsenal 2025-26', 40),
	('arsenal2526-havertz', 'Kai Havertz', 'ST', 'Arsenal 2025-26', 50),
	('arsenal2526-calafiori', 'Riccardo Calafiori', 'CB', 'Arsenal 2025-26', 35),
	('arsenal2526-setford', 'Tommy Setford', 'GK', 'Arsenal 2025-26', 15),
	('arsenal2526-zubimendi', 'Martín Zubimendi', 'CM', 'Arsenal 2025-26', 50),
	('arsenal2526-rice', 'Declan Rice', 'CM', 'Arsenal 2025-26', 100),
	('arsenal2526-lewisskelly', 'Myles Lewis-Skelly', 'LB', 'Arsenal 2025-26', 20),
	('arsenal2526-kiwior', 'Jakub Kiwior', 'CB', 'Arsenal 2025-26', 25),
	('arsenal2526-vieira', 'Fábio Vieira', 'CM', 'Arsenal 2025-26', 30),
	('arsenal2526-nwaneri', 'Ethan Nwaneri', 'CM', 'Arsenal 2025-26', 30),
	('arsenal2526-nelson', 'Reiss Nelson', 'RW', 'Arsenal 2025-26', 40),
	('arsenal2526-hein', 'Karl Hein', 'GK', 'Arsenal 2025-26', 15),
	('arsenal2526-nichols', 'Josh Nichols', 'CB', 'Arsenal 2025-26', 25),
	('arsenal2526-dixon', 'Jaden Dixon', 'RB', 'Arsenal 2025-26', 20),
	('arsenal2526-dowman', 'Max Dowman', 'RW', 'Arsenal 2025-26', 40),
	('arsenal2526-harrimananno', 'Andre Harriman-Annous', 'ST', 'Arsenal 2025-26', 40),
	('arsenal2526-ibrahim', 'Ife Ibrahim', 'CM', 'Arsenal 2025-26', 30),
	('arsenal2526-porter', 'Jack Porter', 'GK', 'Arsenal 2025-26', 15),
	('arsenal2526-baileyjoseph', 'Brando Bailey-Joseph', 'RW', 'Arsenal 2025-26', 40),
	('arsenal2526-salmon', 'Marli Salmon', 'RB', 'Arsenal 2025-26', 20),
	('arsenal2526-jr', 'Charles Sagoe Jr', 'LW', 'Arsenal 2025-26', 40)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'arsenal-25-26'
	and p.metadata ->> 'dev_seed_id' like 'arsenal2526-%'
on conflict do nothing;

-- Liverpool 2025-26 (32 jugadors)
insert into public.tags (slug, display_name, category)
values ('liverpool-25-26', 'Liverpool 2025-26', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('liverpool2526-alisson', 'Alisson', 'GK', 'Liverpool 2025-26', 35),
	('liverpool2526-gomez', 'Joe Gomez', 'CB', 'Liverpool 2025-26', 25),
	('liverpool2526-endo', 'Wataru Endo', 'CM', 'Liverpool 2025-26', 15),
	('liverpool2526-dijk', 'Virgil van Dijk', 'CB', 'Liverpool 2025-26', 25),
	('liverpool2526-konate', 'Ibrahima Konaté', 'CB', 'Liverpool 2025-26', 45),
	('liverpool2526-kerkez', 'Milos Kerkez', 'LB', 'Liverpool 2025-26', 35),
	('liverpool2526-wirtz', 'Florian Wirtz', 'CM', 'Liverpool 2025-26', 100),
	('liverpool2526-szoboszlai', 'Dominik Szoboszlai', 'CM', 'Liverpool 2025-26', 55),
	('liverpool2526-isak', 'Alexander Isak', 'ST', 'Liverpool 2025-26', 90),
	('liverpool2526-allister', 'Alexis Mac Allister', 'CM', 'Liverpool 2025-26', 65),
	('liverpool2526-salah', 'Mohamed Salah', 'RW', 'Liverpool 2025-26', 75),
	('liverpool2526-bradley', 'Conor Bradley', 'RB', 'Liverpool 2025-26', 30),
	('liverpool2526-chiesa', 'Federico Chiesa', 'RW', 'Liverpool 2025-26', 18),
	('liverpool2526-leoni', 'Giovanni Leoni', 'CB', 'Liverpool 2025-26', 25),
	('liverpool2526-jones', 'Curtis Jones', 'CM', 'Liverpool 2025-26', 30),
	('liverpool2526-gakpo', 'Cody Gakpo', 'LW', 'Liverpool 2025-26', 50),
	('liverpool2526-ekitike', 'Hugo Ekitike', 'ST', 'Liverpool 2025-26', 50),
	('liverpool2526-mamardashvil', 'Giorgi Mamardashvili', 'GK', 'Liverpool 2025-26', 25),
	('liverpool2526-robertson', 'Andy Robertson', 'LB', 'Liverpool 2025-26', 22),
	('liverpool2526-woodman', 'Freddie Woodman', 'GK', 'Liverpool 2025-26', 15),
	('liverpool2526-frimpong', 'Jeremie Frimpong', 'RB', 'Liverpool 2025-26', 40),
	('liverpool2526-gravenberch', 'Ryan Gravenberch', 'CM', 'Liverpool 2025-26', 45),
	('liverpool2526-nyoni', 'Trey Nyoni', 'CM', 'Liverpool 2025-26', 30),
	('liverpool2526-ramsay', 'Calvin Ramsay', 'RB', 'Liverpool 2025-26', 20),
	('liverpool2526-gordon', 'Kaide Gordon', 'RW', 'Liverpool 2025-26', 40),
	('liverpool2526-nallo', 'Amara Nallo', 'CB', 'Liverpool 2025-26', 25),
	('liverpool2526-morrison', 'Kieran Morrison', 'CM', 'Liverpool 2025-26', 30),
	('liverpool2526-ngumoha', 'Rio Ngumoha', 'LW', 'Liverpool 2025-26', 40),
	('liverpool2526-danns', 'Jayden Danns', 'ST', 'Liverpool 2025-26', 40),
	('liverpool2526-lucky', 'Wellity Lucky', 'CB', 'Liverpool 2025-26', 25),
	('liverpool2526-elliott', 'Harvey Elliott', 'CM', 'Liverpool 2025-26', 30),
	('liverpool2526-konedoherty', 'Trent Kone-Doherty', 'ST', 'Liverpool 2025-26', 40)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'liverpool-25-26'
	and p.metadata ->> 'dev_seed_id' like 'liverpool2526-%'
on conflict do nothing;

-- PSG 2025-26 (29 jugadors)
insert into public.tags (slug, display_name, category)
values ('psg-25-26', 'PSG 2025-26', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('psg2526-chevalier', 'Lucas Chevalier', 'GK', 'PSG 2025-26', 30),
	('psg2526-safonov', 'Matvey Safonov', 'GK', 'PSG 2025-26', 15),
	('psg2526-marin', 'Renato Marin', 'GK', 'PSG 2025-26', 15),
	('psg2526-hakimi', 'Achraf Hakimi', 'RB', 'PSG 2025-26', 70),
	('psg2526-beraldo', 'Lucas Beraldo', 'LB', 'PSG 2025-26', 20),
	('psg2526-marquinhos', 'Marquinhos', 'CB', 'PSG 2025-26', 35),
	('psg2526-zabarnyi', 'Illia Zabarnyi', 'CB', 'PSG 2025-26', 45),
	('psg2526-hernandez', 'Lucas Hernandez', 'LB', 'PSG 2025-26', 22),
	('psg2526-mendes', 'Nuno Mendes', 'LB', 'PSG 2025-26', 55),
	('psg2526-boly', 'David Boly', 'RB', 'PSG 2025-26', 20),
	('psg2526-pacho', 'Willian Pacho', 'CB', 'PSG 2025-26', 50),
	('psg2526-ruiz', 'Fabián Ruiz', 'CM', 'PSG 2025-26', 45),
	('psg2526-vitinha', 'Vitinha', 'CM', 'PSG 2025-26', 90),
	('psg2526-kangin', 'Lee Kang-in', 'CM', 'PSG 2025-26', 30),
	('psg2526-mayulu', 'Senny Mayulu', 'CM', 'PSG 2025-26', 30),
	('psg2526-fernandez', 'Dro Fernández', 'CM', 'PSG 2025-26', 30),
	('psg2526-zaireemery', 'Warren Zaïre-Emery', 'CM', 'PSG 2025-26', 60),
	('psg2526-jangeal', 'Mathis Jangeal', 'CM', 'PSG 2025-26', 30),
	('psg2526-nsoki', 'Noah Nsoki', 'CM', 'PSG 2025-26', 30),
	('psg2526-neves', 'João Neves', 'CM', 'PSG 2025-26', 90),
	('psg2526-kvaratskheli', 'Khvicha Kvaratskhelia', 'LW', 'PSG 2025-26', 90),
	('psg2526-ramos', 'Gonçalo Ramos', 'ST', 'PSG 2025-26', 40),
	('psg2526-dembele', 'Ousmane Dembélé', 'RW', 'PSG 2025-26', 90),
	('psg2526-doue', 'Désiré Doué', 'RW', 'PSG 2025-26', 80),
	('psg2526-barcola', 'Bradley Barcola', 'ST', 'PSG 2025-26', 65),
	('psg2526-ndjantou', 'Quentin Ndjantou', 'ST', 'PSG 2025-26', 40),
	('psg2526-mbaye', 'Ibrahim Mbaye', 'ST', 'PSG 2025-26', 40),
	('psg2526-mounguengue', 'Pierre Mounguengue', 'ST', 'PSG 2025-26', 40),
	('psg2526-kamara', 'Noham Kamara', 'CB', 'PSG 2025-26', 25)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'psg-25-26'
	and p.metadata ->> 'dev_seed_id' like 'psg2526-%'
on conflict do nothing;

-- Bayern Munich 2025-26 (38 jugadors)
insert into public.tags (slug, display_name, category)
values ('bayern-25-26', 'Bayern Munich 2025-26', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('bayern2526-neuer', 'Manuel Neuer', 'GK', 'Bayern Munich 2025-26', 12),
	('bayern2526-upamecano', 'Dayot Upamecano', 'CB', 'Bayern Munich 2025-26', 55),
	('bayern2526-minjae', 'Kim Min-jae', 'CB', 'Bayern Munich 2025-26', 40),
	('bayern2526-tah', 'Jonathan Tah', 'CB', 'Bayern Munich 2025-26', 40),
	('bayern2526-kimmich', 'Joshua Kimmich', 'CM', 'Bayern Munich 2025-26', 60),
	('bayern2526-gnabry', 'Serge Gnabry', 'RW', 'Bayern Munich 2025-26', 30),
	('bayern2526-goretzka', 'Leon Goretzka', 'CM', 'Bayern Munich 2025-26', 30),
	('bayern2526-kane', 'Harry Kane', 'ST', 'Bayern Munich 2025-26', 70),
	('bayern2526-musiala', 'Jamal Musiala', 'CM', 'Bayern Munich 2025-26', 110),
	('bayern2526-jackson', 'Nicolas Jackson', 'RW', 'Bayern Munich 2025-26', 35),
	('bayern2526-diaz', 'Luis Díaz', 'LW', 'Bayern Munich 2025-26', 50),
	('bayern2526-olise', 'Michael Olise', 'RW', 'Bayern Munich 2025-26', 60),
	('bayern2526-davies', 'Alphonso Davies', 'LB', 'Bayern Munich 2025-26', 60),
	('bayern2526-bischof', 'Tom Bischof', 'CM', 'Bayern Munich 2025-26', 30),
	('bayern2526-ito', 'Hiroki Ito', 'CB', 'Bayern Munich 2025-26', 25),
	('bayern2526-guerreiro', 'Raphaël Guerreiro', 'LB', 'Bayern Munich 2025-26', 20),
	('bayern2526-ulreich', 'Sven Ulreich', 'GK', 'Bayern Munich 2025-26', 15),
	('bayern2526-laimer', 'Konrad Laimer', 'CM', 'Bayern Munich 2025-26', 25),
	('bayern2526-kiala', 'Cassiano Kiala', 'CB', 'Bayern Munich 2025-26', 25),
	('bayern2526-rovere', 'Guido Della Rovere', 'CM', 'Bayern Munich 2025-26', 30),
	('bayern2526-ofli', 'Deniz Ofli', 'LB', 'Bayern Munich 2025-26', 20),
	('bayern2526-bartl', 'Jannis Bärtl', 'GK', 'Bayern Munich 2025-26', 15),
	('bayern2526-mike', 'Wisdom Mike', 'RW', 'Bayern Munich 2025-26', 40),
	('bayern2526-prescott', 'Leonard Prescott', 'GK', 'Bayern Munich 2025-26', 15),
	('bayern2526-osmani', 'Erblin Osmani', 'CM', 'Bayern Munich 2025-26', 30),
	('bayern2526-ndiaye', 'Bara Ndiaye', 'CM', 'Bayern Munich 2025-26', 30),
	('bayern2526-urbig', 'Jonas Urbig', 'GK', 'Bayern Munich 2025-26', 15),
	('bayern2526-manuba', 'Vincent Manuba', 'CB', 'Bayern Munich 2025-26', 25),
	('bayern2526-karl', 'Lennart Karl', 'CM', 'Bayern Munich 2025-26', 30),
	('bayern2526-pavic', 'Filip Pavić', 'CB', 'Bayern Munich 2025-26', 25),
	('bayern2526-stanisic', 'Josip Stanišić', 'CB', 'Bayern Munich 2025-26', 18),
	('bayern2526-pavlovic', 'Aleksandar Pavlović', 'CM', 'Bayern Munich 2025-26', 30),
	('bayern2526-daiber', 'David Santos Daiber', 'CM', 'Bayern Munich 2025-26', 30),
	('bayern2526-klanac', 'Leon Klanac', 'GK', 'Bayern Munich 2025-26', 15),
	('bayern2526-cardozo', 'Maycon Cardozo', 'RW', 'Bayern Munich 2025-26', 40),
	('bayern2526-boey', 'Sacha Boey', 'RB', 'Bayern Munich 2025-26', 20),
	('bayern2526-chavez', 'Felipe Chávez', 'CM', 'Bayern Munich 2025-26', 30),
	('bayern2526-kusiasare', 'Jonah Kusi-Asare', 'ST', 'Bayern Munich 2025-26', 40)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'bayern-25-26'
	and p.metadata ->> 'dev_seed_id' like 'bayern2526-%'
on conflict do nothing;

-- Inter Milan 2025-26 (32 jugadors)
insert into public.tags (slug, display_name, category)
values ('inter-25-26', 'Inter Milan 2025-26', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('inter2526-sommer', 'Yann Sommer', 'GK', 'Inter Milan 2025-26', 8),
	('inter2526-gennaro', 'Raffaele Di Gennaro', 'GK', 'Inter Milan 2025-26', 15),
	('inter2526-martinez', 'Josep Martínez', 'GK', 'Inter Milan 2025-26', 15),
	('inter2526-dumfries', 'Denzel Dumfries', 'RW', 'Inter Milan 2025-26', 30),
	('inter2526-vrij', 'Stefan de Vrij', 'CB', 'Inter Milan 2025-26', 12),
	('inter2526-acerbi', 'Francesco Acerbi', 'CB', 'Inter Milan 2025-26', 6),
	('inter2526-akanji', 'Manuel Akanji', 'CB', 'Inter Milan 2025-26', 25),
	('inter2526-augusto', 'Carlos Augusto', 'LB', 'Inter Milan 2025-26', 20),
	('inter2526-bisseck', 'Yann Aurel Bisseck', 'CB', 'Inter Milan 2025-26', 25),
	('inter2526-dimarco', 'Federico Dimarco', 'LB', 'Inter Milan 2025-26', 50),
	('inter2526-darmian', 'Matteo Darmian', 'CB', 'Inter Milan 2025-26', 25),
	('inter2526-cocchi', 'Matteo Cocchi', 'CB', 'Inter Milan 2025-26', 25),
	('inter2526-bastoni', 'Alessandro Bastoni', 'CB', 'Inter Milan 2025-26', 75),
	('inter2526-zielinski', 'Piotr Zieliński', 'CM', 'Inter Milan 2025-26', 18),
	('inter2526-sucic', 'Petar Sučić', 'CM', 'Inter Milan 2025-26', 25),
	('inter2526-henrique', 'Luis Henrique', 'CM', 'Inter Milan 2025-26', 30),
	('inter2526-frattesi', 'Davide Frattesi', 'CM', 'Inter Milan 2025-26', 30),
	('inter2526-diouf', 'Andy Diouf', 'CM', 'Inter Milan 2025-26', 30),
	('inter2526-calhanoglu', 'Hakan Çalhanoğlu', 'CM', 'Inter Milan 2025-26', 35),
	('inter2526-mkhitaryan', 'Henrikh Mkhitaryan', 'CM', 'Inter Milan 2025-26', 12),
	('inter2526-barella', 'Nicolò Barella', 'CM', 'Inter Milan 2025-26', 80),
	('inter2526-kamate', 'Issiaka Kamate', 'CM', 'Inter Milan 2025-26', 30),
	('inter2526-bovo', 'Leonardo Bovo', 'CM', 'Inter Milan 2025-26', 30),
	('inter2526-thuram', 'Marcus Thuram', 'ST', 'Inter Milan 2025-26', 70),
	('inter2526-martinez2', 'Lautaro Martínez', 'ST', 'Inter Milan 2025-26', 90),
	('inter2526-bonny', 'Ange-Yoan Bonny', 'ST', 'Inter Milan 2025-26', 40),
	('inter2526-spinacce', 'Matteo Spinaccè', 'ST', 'Inter Milan 2025-26', 40),
	('inter2526-mosconi', 'Mattia Mosconi', 'ST', 'Inter Milan 2025-26', 40),
	('inter2526-lavelli', 'Matteo Lavelli', 'ST', 'Inter Milan 2025-26', 40),
	('inter2526-esposito', 'Pio Esposito', 'ST', 'Inter Milan 2025-26', 40),
	('inter2526-pavard', 'Benjamin Pavard', 'CB', 'Inter Milan 2025-26', 35),
	('inter2526-palacios', 'Tomás Palacios', 'CB', 'Inter Milan 2025-26', 25)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'inter-25-26'
	and p.metadata ->> 'dev_seed_id' like 'inter2526-%'
on conflict do nothing;

-- Napoli 2025-26 (43 jugadors)
insert into public.tags (slug, display_name, category)
values ('napoli-25-26', 'Napoli 2025-26', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('napoli2526-meret', 'Alex Meret', 'GK', 'Napoli 2025-26', 15),
	('napoli2526-gutierrez', 'Miguel Gutiérrez', 'LW', 'Napoli 2025-26', 40),
	('napoli2526-buongiorno', 'Alessandro Buongiorno', 'CB', 'Napoli 2025-26', 40),
	('napoli2526-jesus', 'Juan Jesus', 'CB', 'Napoli 2025-26', 25),
	('napoli2526-gilmour', 'Billy Gilmour', 'CM', 'Napoli 2025-26', 22),
	('napoli2526-neres', 'David Neres', 'RW', 'Napoli 2025-26', 35),
	('napoli2526-mctominay', 'Scott McTominay', 'CM', 'Napoli 2025-26', 50),
	('napoli2526-lukaku', 'Romelu Lukaku', 'ST', 'Napoli 2025-26', 25),
	('napoli2526-bruyne', 'Kevin De Bruyne', 'CM', 'Napoli 2025-26', 30),
	('napoli2526-rrahmani', 'Amir Rrahmani', 'CB', 'Napoli 2025-26', 22),
	('napoli2526-contini', 'Nikita Contini', 'GK', 'Napoli 2025-26', 15),
	('napoli2526-olivera', 'Mathías Olivera', 'LB', 'Napoli 2025-26', 22),
	('napoli2526-hjlund', 'Rasmus Højlund', 'ST', 'Napoli 2025-26', 45),
	('napoli2526-elmas', 'Eljif Elmas', 'CM', 'Napoli 2025-26', 30),
	('napoli2526-politano', 'Matteo Politano', 'RW', 'Napoli 2025-26', 40),
	('napoli2526-lorenzo', 'Giovanni Di Lorenzo', 'RB', 'Napoli 2025-26', 30),
	('napoli2526-giovane', 'Giovane', 'ST', 'Napoli 2025-26', 40),
	('napoli2526-vergara', 'Antonio Vergara', 'CM', 'Napoli 2025-26', 30),
	('napoli2526-santos', 'Alisson Santos', 'RW', 'Napoli 2025-26', 40),
	('napoli2526-mazzocchi', 'Pasquale Mazzocchi', 'CB', 'Napoli 2025-26', 25),
	('napoli2526-beukema', 'Sam Beukema', 'CB', 'Napoli 2025-26', 25),
	('napoli2526-milinkovicsa', 'Vanja Milinković-Savić', 'GK', 'Napoli 2025-26', 15),
	('napoli2526-spinazzola', 'Leonardo Spinazzola', 'LW', 'Napoli 2025-26', 40),
	('napoli2526-lobotka', 'Stanislav Lobotka', 'CM', 'Napoli 2025-26', 30),
	('napoli2526-anguissa', 'André-Frank Zambo Anguissa', 'CM', 'Napoli 2025-26', 30),
	('napoli2526-marianucci', 'Luca Marianucci', 'CB', 'Napoli 2025-26', 25),
	('napoli2526-marin', 'Rafa Marín', 'CB', 'Napoli 2025-26', 25),
	('napoli2526-zanoli', 'Alessandro Zanoli', 'RB', 'Napoli 2025-26', 20),
	('napoli2526-cajuste', 'Jens Cajuste', 'CM', 'Napoli 2025-26', 30),
	('napoli2526-folorunsho', 'Michael Folorunsho', 'CM', 'Napoli 2025-26', 30),
	('napoli2526-saco', 'Coli Saco', 'CM', 'Napoli 2025-26', 30),
	('napoli2526-ambrosino', 'Giuseppe Ambrosino', 'ST', 'Napoli 2025-26', 40),
	('napoli2526-cheddira', 'Walid Cheddira', 'ST', 'Napoli 2025-26', 40),
	('napoli2526-cioffi', 'Antonio Cioffi', 'ST', 'Napoli 2025-26', 40),
	('napoli2526-hasa', 'Luis Hasa', 'ST', 'Napoli 2025-26', 40),
	('napoli2526-lang', 'Noa Lang', 'LW', 'Napoli 2025-26', 30),
	('napoli2526-lindstrm', 'Jesper Lindstrøm', 'RW', 'Napoli 2025-26', 40),
	('napoli2526-lucca', 'Lorenzo Lucca', 'ST', 'Napoli 2025-26', 25),
	('napoli2526-ngonge', 'Cyril Ngonge', 'ST', 'Napoli 2025-26', 40),
	('napoli2526-rao', 'Emanuele Rao', 'RW', 'Napoli 2025-26', 40),
	('napoli2526-sgarbi', 'Lorenzo Sgarbi', 'ST', 'Napoli 2025-26', 40),
	('napoli2526-simeone', 'Giovanni Simeone', 'ST', 'Napoli 2025-26', 40),
	('napoli2526-zerbin', 'Alessio Zerbin', 'RW', 'Napoli 2025-26', 40)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'napoli-25-26'
	and p.metadata ->> 'dev_seed_id' like 'napoli2526-%'
on conflict do nothing;

