-- ============================================================================
-- Real seed: UCL històric — 7 guanyadors de la Champions dels 2010.
-- Auto-generated by scripts/build-ucl-seeds.mjs from
-- scripts/ucl-squads-raw.json + inline hand-curated squads (Bayern 12-13,
-- Liverpool 18-19) for seasons whose Wikipedia pages lack squad tables.
-- Generated: 2026-05-13T09:13:20.110Z
-- ============================================================================

-- Inter Milan 2009-10 (UCL winner) (32 jugadors)
insert into public.tags (slug, display_name, category)
values ('inter-2009-10', 'Inter Milan 2009-10', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('inter0910-cesar', 'Julio Cesar', 'GK', 'Inter Milan 2009-10', 15),
	('inter0910-maicon', 'Maicon', 'RB', 'Inter Milan 2009-10', 25),
	('inter0910-lucio', 'Lúcio', 'CB', 'Inter Milan 2009-10', 18),
	('inter0910-samuel', 'Walter Samuel', 'CB', 'Inter Milan 2009-10', 12),
	('inter0910-chivu', 'Christian Chivu', 'CB', 'Inter Milan 2009-10', 6),
	('inter0910-zanetti', 'Javier Zanetti', 'RB', 'Inter Milan 2009-10', 15),
	('inter0910-cambiasso', 'Esteban Cambiasso', 'CM', 'Inter Milan 2009-10', 18),
	('inter0910-sneijder', 'Wesley Sneijder', 'CM', 'Inter Milan 2009-10', 30),
	('inter0910-stankovic', 'Dejan Stankovic', 'CM', 'Inter Milan 2009-10', 15),
	('inter0910-milito', 'Diego Milito', 'ST', 'Inter Milan 2009-10', 25),
	('inter0910-etoo', 'Samuel Eto''o', 'RW', 'Inter Milan 2009-10', 35),
	('inter0910-toldo', 'Francesco Toldo', 'GK', 'Inter Milan 2009-10', 8),
	('inter0910-motta', 'Thiago Motta', 'CM', 'Inter Milan 2009-10', 15),
	('inter0910-muntari', 'Sulley Ali Muntari', 'CM', 'Inter Milan 2009-10', 15),
	('inter0910-cordoba', 'Ivan Cordoba', 'CB', 'Inter Milan 2009-10', 4),
	('inter0910-balotelli', 'Mario Balotelli', 'ST', 'Inter Milan 2009-10', 12),
	('inter0910-pandev', 'Goran Pandev', 'ST', 'Inter Milan 2009-10', 8),
	('inter0910-santon', 'Davide Santon', 'CB', 'Inter Milan 2009-10', 12),
	('inter0910-materazzi', 'Marco Materazzi', 'CB', 'Inter Milan 2009-10', 4),
	('inter0910-vieira', 'Patrick Vieira', 'CM', 'Inter Milan 2009-10', 6),
	('inter0910-quaresma', 'Ricardo Quaresma', 'CM', 'Inter Milan 2009-10', 15),
	('inter0910-mariga', 'McDonald Mariga', 'CM', 'Inter Milan 2009-10', 15),
	('inter0910-krhin', 'Rene Krhin', 'CM', 'Inter Milan 2009-10', 15),
	('inter0910-orlandoni', 'Paolo Orlandoni', 'GK', 'Inter Milan 2009-10', 8),
	('inter0910-donati', 'Giulio Donati', 'RB', 'Inter Milan 2009-10', 10),
	('inter0910-stevanovic', 'Alen Stevanovic', 'CM', 'Inter Milan 2009-10', 15),
	('inter0910-mancini', 'Amantino Mancini', 'CM', 'Inter Milan 2009-10', 15),
	('inter0910-suazo', 'David Suazo', 'ST', 'Inter Milan 2009-10', 18),
	('inter0910-arnautovic', 'Marko Arnautovic', 'ST', 'Inter Milan 2009-10', 18),
	('inter0910-crisetig', 'Lorenzo Crisetig', 'CM', 'Inter Milan 2009-10', 15),
	('inter0910-alibec', 'Denis Alibec', 'ST', 'Inter Milan 2009-10', 18),
	('inter0910-carlsen', 'Sebastian Carlsen', 'CM', 'Inter Milan 2009-10', 15)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'inter-2009-10'
	and p.metadata ->> 'dev_seed_id' like 'inter0910-%'
on conflict do nothing;

-- Chelsea 2011-12 (UCL winner) (44 jugadors)
insert into public.tags (slug, display_name, category)
values ('chelsea-2011-12', 'Chelsea 2011-12', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('chelsea1112-cech', 'Petr Čech', 'GK', 'Chelsea 2011-12', 18),
	('chelsea1112-ivanovic', 'Branislav Ivanović', 'CB', 'Chelsea 2011-12', 18),
	('chelsea1112-cole', 'Ashley Cole', 'LB', 'Chelsea 2011-12', 18),
	('chelsea1112-luiz', 'David Luiz', 'CB', 'Chelsea 2011-12', 20),
	('chelsea1112-essien', 'Michael Essien', 'CM', 'Chelsea 2011-12', 14),
	('chelsea1112-romeu', 'Oriol Romeu', 'CM', 'Chelsea 2011-12', 15),
	('chelsea1112-ramires', 'Ramires', 'CM', 'Chelsea 2011-12', 20),
	('chelsea1112-lampard', 'Frank Lampard', 'CM', 'Chelsea 2011-12', 18),
	('chelsea1112-torres', 'Fernando Torres', 'ST', 'Chelsea 2011-12', 30),
	('chelsea1112-mata', 'Juan Mata', 'CM', 'Chelsea 2011-12', 35),
	('chelsea1112-drogba', 'Didier Drogba', 'ST', 'Chelsea 2011-12', 25),
	('chelsea1112-obi', 'Mikel John Obi', 'CM', 'Chelsea 2011-12', 8),
	('chelsea1112-malouda', 'Florent Malouda', 'CM', 'Chelsea 2011-12', 6),
	('chelsea1112-meireles', 'Raul Meireles', 'CM', 'Chelsea 2011-12', 15),
	('chelsea1112-bosingwa', 'José Bosingwa', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-lukaku', 'Romelu Lukaku', 'ST', 'Chelsea 2011-12', 18),
	('chelsea1112-ferreira', 'Paulo Ferreira', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-mceachran', 'Josh McEachran', 'CM', 'Chelsea 2011-12', 15),
	('chelsea1112-kalou', 'Salomon Kalou', 'ST', 'Chelsea 2011-12', 6),
	('chelsea1112-turnbull', 'Ross Turnbull', 'GK', 'Chelsea 2011-12', 8),
	('chelsea1112-sturridge', 'Daniel Sturridge', 'ST', 'Chelsea 2011-12', 12),
	('chelsea1112-cahill', 'Gary Cahill', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-terry', 'John Terry', 'CB', 'Chelsea 2011-12', 20),
	('chelsea1112-hutchinson', 'Sam Hutchinson', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-bertrand', 'Ryan Bertrand', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-piazon', 'Lucas Piazon', 'CM', 'Chelsea 2011-12', 15),
	('chelsea1112-hilario', 'Henrique Hilário', 'GK', 'Chelsea 2011-12', 8),
	('chelsea1112-chalobah', 'Nathaniel Chalobah', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-blackman', 'Jamal Blackman', 'GK', 'Chelsea 2011-12', 8),
	('chelsea1112-clifford', 'Billy Clifford', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-clifford2', 'Conor Clifford', 'CM', 'Chelsea 2011-12', 15),
	('chelsea1112-deenconteh', 'Aziz Deen-Conteh', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-ince', 'Rohan Ince', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-mitrovic', 'Marko Mitrović', 'ST', 'Chelsea 2011-12', 18),
	('chelsea1112-kane', 'Todd Kane', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-saville', 'George Saville', 'CM', 'Chelsea 2011-12', 15),
	('chelsea1112-pappoe', 'Daniel Pappoe', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-phillip', 'Adam Phillip', 'ST', 'Chelsea 2011-12', 18),
	('chelsea1112-supbsup', 'James Ashton <sup>B</sup>', 'CM', 'Chelsea 2011-12', 15),
	('chelsea1112-nkumu', 'Archange Nkumu', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-taylor', 'Rhys Taylor', 'GK', 'Chelsea 2011-12', 8),
	('chelsea1112-benayoun', 'Yossi Benayoun', 'CM', 'Chelsea 2011-12', 15),
	('chelsea1112-alex', 'Alex', 'CB', 'Chelsea 2011-12', 12),
	('chelsea1112-anelka', 'Nicolas Anelka', 'ST', 'Chelsea 2011-12', 18)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'chelsea-2011-12'
	and p.metadata ->> 'dev_seed_id' like 'chelsea1112-%'
on conflict do nothing;

-- Bayern Munich 2012-13 (UCL winner) (22 jugadors)
insert into public.tags (slug, display_name, category)
values ('bayern-2012-13', 'Bayern Munich 2012-13', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('bayern1213-neuer', 'Manuel Neuer', 'GK', 'Bayern Munich 2012-13', 25),
	('bayern1213-starke', 'Tom Starke', 'GK', 'Bayern Munich 2012-13', 8),
	('bayern1213-lahm', 'Philipp Lahm', 'RB', 'Bayern Munich 2012-13', 22),
	('bayern1213-rafinha', 'Rafinha', 'RB', 'Bayern Munich 2012-13', 10),
	('bayern1213-alaba', 'David Alaba', 'LB', 'Bayern Munich 2012-13', 25),
	('bayern1213-contento', 'Diego Contento', 'LB', 'Bayern Munich 2012-13', 10),
	('bayern1213-boateng', 'Jérôme Boateng', 'CB', 'Bayern Munich 2012-13', 18),
	('bayern1213-dante', 'Dante', 'CB', 'Bayern Munich 2012-13', 14),
	('bayern1213-badstuber', 'Holger Badstuber', 'CB', 'Bayern Munich 2012-13', 12),
	('bayern1213-buyten', 'Daniel Van Buyten', 'CB', 'Bayern Munich 2012-13', 12),
	('bayern1213-schweinsteig', 'Bastian Schweinsteiger', 'CM', 'Bayern Munich 2012-13', 25),
	('bayern1213-martinez', 'Javi Martínez', 'CM', 'Bayern Munich 2012-13', 22),
	('bayern1213-kroos', 'Toni Kroos', 'CM', 'Bayern Munich 2012-13', 22),
	('bayern1213-gustavo', 'Luiz Gustavo', 'CM', 'Bayern Munich 2012-13', 15),
	('bayern1213-tymoshchuk', 'Anatoliy Tymoshchuk', 'CM', 'Bayern Munich 2012-13', 15),
	('bayern1213-robben', 'Arjen Robben', 'RW', 'Bayern Munich 2012-13', 25),
	('bayern1213-shaqiri', 'Xherdan Shaqiri', 'RW', 'Bayern Munich 2012-13', 12),
	('bayern1213-ribery', 'Franck Ribéry', 'LW', 'Bayern Munich 2012-13', 28),
	('bayern1213-muller', 'Thomas Müller', 'ST', 'Bayern Munich 2012-13', 30),
	('bayern1213-mandzukic', 'Mario Mandžukić', 'ST', 'Bayern Munich 2012-13', 18),
	('bayern1213-gomez', 'Mario Gómez', 'ST', 'Bayern Munich 2012-13', 18),
	('bayern1213-pizarro', 'Claudio Pizarro', 'ST', 'Bayern Munich 2012-13', 18)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'bayern-2012-13'
	and p.metadata ->> 'dev_seed_id' like 'bayern1213-%'
on conflict do nothing;

-- Real Madrid 2015-16 (UCL winner) (27 jugadors)
insert into public.tags (slug, display_name, category)
values ('madrid-2015-16', 'Real Madrid 2015-16', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('madrid1516-navas', 'Keylor Navas', 'GK', 'Real Madrid 2015-16', 22),
	('madrid1516-danilo', 'Danilo', 'RB', 'Real Madrid 2015-16', 10),
	('madrid1516-ramos', 'Sergio Ramos', 'CB', 'Real Madrid 2015-16', 35),
	('madrid1516-varane', 'Raphaël Varane', 'CB', 'Real Madrid 2015-16', 30),
	('madrid1516-marcelo', 'Marcelo', 'LB', 'Real Madrid 2015-16', 28),
	('madrid1516-modric', 'Luka Modrić', 'CM', 'Real Madrid 2015-16', 45),
	('madrid1516-kroos', 'Toni Kroos', 'CM', 'Real Madrid 2015-16', 55),
	('madrid1516-isco', 'Isco', 'LW', 'Real Madrid 2015-16', 35),
	('madrid1516-ronaldo', 'Cristiano Ronaldo', 'LW', 'Real Madrid 2015-16', 110),
	('madrid1516-benzema', 'Karim Benzema', 'ST', 'Real Madrid 2015-16', 40),
	('madrid1516-bale', 'Gareth Bale', 'RW', 'Real Madrid 2015-16', 80),
	('madrid1516-casilla', 'Kiko Casilla', 'GK', 'Real Madrid 2015-16', 8),
	('madrid1516-pepe', 'Pepe', 'CB', 'Real Madrid 2015-16', 15),
	('madrid1516-carvajal', 'Dani Carvajal', 'RB', 'Real Madrid 2015-16', 22),
	('madrid1516-rodriguez', 'James Rodríguez', 'CM', 'Real Madrid 2015-16', 60),
	('madrid1516-casemiro', 'Casemiro', 'CM', 'Real Madrid 2015-16', 25),
	('madrid1516-nacho', 'Nacho', 'CB', 'Real Madrid 2015-16', 12),
	('madrid1516-vazquez', 'Lucas Vázquez', 'RW', 'Real Madrid 2015-16', 12),
	('madrid1516-kovacic', 'Mateo Kovačić', 'CM', 'Real Madrid 2015-16', 25),
	('madrid1516-jese', 'Jesé', 'ST', 'Real Madrid 2015-16', 18),
	('madrid1516-mayoral', 'Borja Mayoral', 'ST', 'Real Madrid 2015-16', 18),
	('madrid1516-arbeloa', 'Álvaro Arbeloa', 'CB', 'Real Madrid 2015-16', 12),
	('madrid1516-cheryshev', 'Denis Cheryshev', 'LW', 'Real Madrid 2015-16', 18),
	('madrid1516-llorente', 'Marcos Llorente', 'CM', 'Real Madrid 2015-16', 15),
	('madrid1516-yanez', 'Rubén Yáñez', 'GK', 'Real Madrid 2015-16', 8),
	('madrid1516-lienhart', 'Philipp Lienhart', 'CB', 'Real Madrid 2015-16', 12),
	('madrid1516-tejero', 'Álvaro Tejero', 'CB', 'Real Madrid 2015-16', 12)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'madrid-2015-16'
	and p.metadata ->> 'dev_seed_id' like 'madrid1516-%'
on conflict do nothing;

-- Real Madrid 2017-18 (UCL winner) (29 jugadors)
insert into public.tags (slug, display_name, category)
values ('madrid-2017-18', 'Real Madrid 2017-18', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('madrid1718-navas', 'Keylor Navas', 'GK', 'Real Madrid 2017-18', 20),
	('madrid1718-carvajal', 'Dani Carvajal', 'RB', 'Real Madrid 2017-18', 32),
	('madrid1718-ramos', 'Sergio Ramos', 'CB', 'Real Madrid 2017-18', 38),
	('madrid1718-varane', 'Raphaël Varane', 'CB', 'Real Madrid 2017-18', 50),
	('madrid1718-marcelo', 'Marcelo', 'LB', 'Real Madrid 2017-18', 35),
	('madrid1718-kroos', 'Toni Kroos', 'CM', 'Real Madrid 2017-18', 70),
	('madrid1718-modric', 'Luka Modrić', 'CM', 'Real Madrid 2017-18', 60),
	('madrid1718-casemiro', 'Casemiro', 'CM', 'Real Madrid 2017-18', 50),
	('madrid1718-ronaldo', 'Cristiano Ronaldo', 'LW', 'Real Madrid 2017-18', 100),
	('madrid1718-benzema', 'Karim Benzema', 'ST', 'Real Madrid 2017-18', 45),
	('madrid1718-bale', 'Gareth Bale', 'RW', 'Real Madrid 2017-18', 70),
	('madrid1718-casilla', 'Kiko Casilla', 'GK', 'Real Madrid 2017-18', 8),
	('madrid1718-nacho', 'Nacho', 'CB', 'Real Madrid 2017-18', 12),
	('madrid1718-isco', 'Isco', 'LW', 'Real Madrid 2017-18', 60),
	('madrid1718-asensio', 'Marco Asensio', 'RW', 'Real Madrid 2017-18', 55),
	('madrid1718-vazquez', 'Lucas Vázquez', 'RW', 'Real Madrid 2017-18', 18),
	('madrid1718-kovacic', 'Mateo Kovačić', 'CM', 'Real Madrid 2017-18', 30),
	('madrid1718-hernandez', 'Théo Hernandez', 'CB', 'Real Madrid 2017-18', 25),
	('madrid1718-hakimi', 'Achraf Hakimi', 'RB', 'Real Madrid 2017-18', 18),
	('madrid1718-vallejo', 'Jesús Vallejo', 'CB', 'Real Madrid 2017-18', 12),
	('madrid1718-llorente', 'Marcos Llorente', 'CM', 'Real Madrid 2017-18', 15),
	('madrid1718-ceballos', 'Dani Ceballos', 'CM', 'Real Madrid 2017-18', 15),
	('madrid1718-mayoral', 'Borja Mayoral', 'ST', 'Real Madrid 2017-18', 18),
	('madrid1718-zidane', 'Luca Zidane', 'GK', 'Real Madrid 2017-18', 8),
	('madrid1718-tejero', 'Álvaro Tejero', 'CB', 'Real Madrid 2017-18', 12),
	('madrid1718-feuillassier', 'Francisco Feuillassier', 'CM', 'Real Madrid 2017-18', 15),
	('madrid1718-quezada', 'Luismi Quezada', 'CB', 'Real Madrid 2017-18', 12),
	('madrid1718-rodriguez', 'Óscar Rodríguez', 'CM', 'Real Madrid 2017-18', 15),
	('madrid1718-seoane', 'Jaime Seoane', 'CM', 'Real Madrid 2017-18', 15)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'madrid-2017-18'
	and p.metadata ->> 'dev_seed_id' like 'madrid1718-%'
on conflict do nothing;

-- Liverpool 2018-19 (UCL winner) (22 jugadors)
insert into public.tags (slug, display_name, category)
values ('liverpool-2018-19', 'Liverpool 2018-19', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('liverpool1819-alisson', 'Alisson', 'GK', 'Liverpool 2018-19', 50),
	('liverpool1819-mignolet', 'Simon Mignolet', 'GK', 'Liverpool 2018-19', 8),
	('liverpool1819-alexanderarn', 'Trent Alexander-Arnold', 'RB', 'Liverpool 2018-19', 45),
	('liverpool1819-robertson', 'Andrew Robertson', 'LB', 'Liverpool 2018-19', 40),
	('liverpool1819-moreno', 'Alberto Moreno', 'LB', 'Liverpool 2018-19', 10),
	('liverpool1819-dijk', 'Virgil van Dijk', 'CB', 'Liverpool 2018-19', 75),
	('liverpool1819-matip', 'Joël Matip', 'CB', 'Liverpool 2018-19', 18),
	('liverpool1819-lovren', 'Dejan Lovren', 'CB', 'Liverpool 2018-19', 14),
	('liverpool1819-gomez', 'Joe Gomez', 'CB', 'Liverpool 2018-19', 12),
	('liverpool1819-henderson', 'Jordan Henderson', 'CM', 'Liverpool 2018-19', 25),
	('liverpool1819-wijnaldum', 'Georginio Wijnaldum', 'CM', 'Liverpool 2018-19', 30),
	('liverpool1819-fabinho', 'Fabinho', 'CM', 'Liverpool 2018-19', 45),
	('liverpool1819-milner', 'James Milner', 'CM', 'Liverpool 2018-19', 8),
	('liverpool1819-keita', 'Naby Keïta', 'CM', 'Liverpool 2018-19', 30),
	('liverpool1819-lallana', 'Adam Lallana', 'CM', 'Liverpool 2018-19', 15),
	('liverpool1819-salah', 'Mohamed Salah', 'RW', 'Liverpool 2018-19', 80),
	('liverpool1819-shaqiri', 'Xherdan Shaqiri', 'RW', 'Liverpool 2018-19', 14),
	('liverpool1819-mane', 'Sadio Mané', 'LW', 'Liverpool 2018-19', 70),
	('liverpool1819-firmino', 'Roberto Firmino', 'ST', 'Liverpool 2018-19', 60),
	('liverpool1819-origi', 'Divock Origi', 'ST', 'Liverpool 2018-19', 8),
	('liverpool1819-sturridge', 'Daniel Sturridge', 'ST', 'Liverpool 2018-19', 10),
	('liverpool1819-solanke', 'Dominic Solanke', 'ST', 'Liverpool 2018-19', 18)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'liverpool-2018-19'
	and p.metadata ->> 'dev_seed_id' like 'liverpool1819-%'
on conflict do nothing;

-- Bayern Munich 2019-20 (UCL winner) (37 jugadors)
insert into public.tags (slug, display_name, category)
values ('bayern-2019-20', 'Bayern Munich 2019-20', 'club_season')
on conflict (slug) do nothing;

insert into public.players (name, primary_position, market_value_cents, is_scrub, metadata)
select v.name, v.pos::position_code, (v.value_m::bigint) * 100000000, false,
	jsonb_build_object('dev_seed_id', v.seed_id, 'team', v.team)
from (values
	('bayern1920-neuer', 'Manuel Neuer', 'GK', 'Bayern Munich 2019-20', 18),
	('bayern1920-odriozola', 'Álvaro Odriozola', 'RB', 'Bayern Munich 2019-20', 15),
	('bayern1920-sule', 'Niklas Süle', 'CB', 'Bayern Munich 2019-20', 35),
	('bayern1920-pavard', 'Benjamin Pavard', 'CB', 'Bayern Munich 2019-20', 35),
	('bayern1920-thiago', 'Thiago', 'CM', 'Bayern Munich 2019-20', 50),
	('bayern1920-gnabry', 'Serge Gnabry', 'RW', 'Bayern Munich 2019-20', 60),
	('bayern1920-martinez', 'Javi Martínez', 'CM', 'Bayern Munich 2019-20', 12),
	('bayern1920-lewandowski', 'Robert Lewandowski', 'ST', 'Bayern Munich 2019-20', 80),
	('bayern1920-coutinho', 'Philippe Coutinho', 'CM', 'Bayern Munich 2019-20', 50),
	('bayern1920-coman', 'Kingsley Coman', 'LW', 'Bayern Munich 2019-20', 45),
	('bayern1920-perisic', 'Ivan Perišić', 'CM', 'Bayern Munich 2019-20', 12),
	('bayern1920-boateng', 'Jérôme Boateng', 'CB', 'Bayern Munich 2019-20', 15),
	('bayern1920-goretzka', 'Leon Goretzka', 'CM', 'Bayern Munich 2019-20', 45),
	('bayern1920-davies', 'Alphonso Davies', 'LB', 'Bayern Munich 2019-20', 65),
	('bayern1920-hernandez', 'Lucas Hernandez', 'LB', 'Bayern Munich 2019-20', 10),
	('bayern1920-tolisso', 'Corentin Tolisso', 'CM', 'Bayern Munich 2019-20', 20),
	('bayern1920-muller', 'Thomas Müller', 'ST', 'Bayern Munich 2019-20', 30),
	('bayern1920-ulreich', 'Sven Ulreich', 'GK', 'Bayern Munich 2019-20', 8),
	('bayern1920-alaba', 'David Alaba', 'LB', 'Bayern Munich 2019-20', 60),
	('bayern1920-kimmich', 'Joshua Kimmich', 'CM', 'Bayern Munich 2019-20', 65),
	('bayern1920-zirkzee', 'Joshua Zirkzee', 'ST', 'Bayern Munich 2019-20', 18),
	('bayern1920-richards', 'Chris Richards', 'CB', 'Bayern Munich 2019-20', 12),
	('bayern1920-musiala', 'Jamal Musiala', 'CM', 'Bayern Munich 2019-20', 15),
	('bayern1920-fruchtl', 'Christian Früchtl', 'GK', 'Bayern Munich 2019-20', 8),
	('bayern1920-hoffmann', 'Ron-Thorben Hoffmann', 'GK', 'Bayern Munich 2019-20', 8),
	('bayern1920-mai', 'Lars Lukas Mai', 'CB', 'Bayern Munich 2019-20', 12),
	('bayern1920-arreymbi', 'Bright Arrey-Mbi', 'CB', 'Bayern Munich 2019-20', 12),
	('bayern1920-cuisance', 'Michaël Cuisance', 'CM', 'Bayern Munich 2019-20', 15),
	('bayern1920-dajaku', 'Leon Dajaku', 'CM', 'Bayern Munich 2019-20', 15),
	('bayern1920-singh', 'Sarpreet Singh', 'CM', 'Bayern Munich 2019-20', 15),
	('bayern1920-meier', 'Oliver Batista Meier', 'CM', 'Bayern Munich 2019-20', 15),
	('bayern1920-will', 'Paul Will', 'CM', 'Bayern Munich 2019-20', 15),
	('bayern1920-tillman', 'Malik Tillman', 'CM', 'Bayern Munich 2019-20', 15),
	('bayern1920-arp', 'Jann-Fiete Arp', 'ST', 'Bayern Munich 2019-20', 18),
	('bayern1920-wooyeong', 'Jeong Woo-yeong', 'ST', 'Bayern Munich 2019-20', 18),
	('bayern1920-sanches', 'Renato Sanches', 'CM', 'Bayern Munich 2019-20', 15),
	('bayern1920-wriedt', 'Kwasi Okyere Wriedt', 'ST', 'Bayern Munich 2019-20', 18)
) as v(seed_id, name, pos, team, value_m)
where not exists (
	select 1 from public.players where metadata ->> 'dev_seed_id' = v.seed_id
);

insert into public.player_tags (player_id, tag_id)
select p.id, t.id
from public.players p
cross join public.tags t
where t.slug = 'bayern-2019-20'
	and p.metadata ->> 'dev_seed_id' like 'bayern1920-%'
on conflict do nothing;

